[tool.poetry]
name = "topic_modeling"
version = "0.1.0"
description = ""
authors = ["dev <nlp@thedeep.io"]

[tool.poetry.dependencies]
python = ">=3.8"
pillow = "==9.0.0"
boto3 = "*"
psycopg2-binary = "*"
topic_generator = { git = "https://github.com/ranjan-stha/topic-generator", rev = "4ab83c2c176e6cf2134288746523e54e5101fcc2", branch = "main" }


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
